config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:create]
  end
  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
require_relative '../uploaders/photo_uploader'
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true, allow_blank: false
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  before_destroy :prevent_destroy
  validates :name, uniqueness: true, presence: true
  has_many :doses
  has_many :cocktails, through: :doses

  private

  def prevent_destroy
    Dose.find_by(ingredient: self).nil? ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :update, :destroy, :edit]
  def show
    @dose = Dose.new(cocktail_id: @cocktail.id)
  end

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    cocktail = Cocktail.new(cocktail_params)
    if cocktail.valid?
      @cocktail = cocktail
      @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      @cocktail = cocktail
      render new_cocktail_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:destroy]

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.valid?
      @dose.save
      redirect_to cocktail_path(@cocktail.id)
    else
      errors @cocktail.errors
      render "cocktails/show"
    end
  end

  def destroy
    @dose.destroy
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Update the <%= @cocktail.name  %>'s recipe</h1>


<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/index.html.erb
<div class="wrapper">
  <div class="home-background" style="background-image: url(<%= asset_path 'home-bar.jpg' %>); height: 500px"></div>
  <div class="container">
    <h2 class="page-header text-center">cocktails</h2>
    <div class="row">
      <% @cocktails.each do |cocktail|  %>
        <div class="col-3">
          <%= link_to cocktail_path(cocktail.id) do %>
            <div class="card" style="width: 80%;">
              <% url="'https://loremflickr.com/g/320/240/#{cocktail.name.downcase}'" %>
              <div class="card-img-top" style="background-image: url(<%= url  %>); background-repeat: no-repeat;background-size: cover;">
                <div class="card-title text-center">
                  <h2> - <%= cocktail.name.downcase %> - </h2>
                </div>
              </div>
            </div>
          <% end  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<div class= "wrapper">
  <div style="height: 80px; width: 100%"></div>
  <div class="cocktail-container">


  <div class="cocktail-background"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path @cocktail.photo, height: 300, width: 576, crop: :fill %>')">
   </div>
   <div class="recipe-card">
      <div class="recipe-title">
        <%= @cocktail.name.upcase  %>
      </div>
      <div class="recipe-ingredients">
        <div class="section-title">
          Ingredients
        </div>
        <div class="ingredients-list">
          <ul>
            <% @cocktail.ingredients.each do |ingredient|%>
              <p> <%= ingredient.name %></p>
            <% end %>
          </ul>
        </div>
        <!-- <%= render 'doses/form', {cocktail: @cocktail, dose: @dose} %> -->
      </div>
      <div class="recipe-instructions">
        <div class="section-title">
          Instructions
        </div>
        <ol>
          <li>Open stuff</li>
          <li>Mix stuff</li>
          <li>Drink stuff</li>
        </ol>
      </div>
    </div>

   </div>

  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
   <%= f.association :ingredient %>
   <%= f.input :description %>
   <%= f.button :submit %>
 <% end %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h1>Add a new ingredient</h1>

<%= render 'form', {cocktail: @cocktail} %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#upodate</h1>
<p>Find me in app/views/doses/upodate.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar-wagon navbar-fixed-top">
    <%= link_to 'D R I N K S', cocktails_path, class: 'navbar-brand' %>

    <div class="navbar-wagon-right">
      <div class="form-inline">
<!--         <form action="">
          <input type="text" name="search_value" class="form-control">
          <input type="submit" class="btn btn-outline-success" value="search">
 -->          <%= link_to 'add drinks', new_cocktail_path, class: 'btn btn-outline-primary' %>
        <!-- </form> -->
      </div>
    </div>


  </nav>

    <%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>